name: Release
on:
  push:
    tags:
      - "**"
    branches-ignore:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set POM Version
        run: mvn versions:set versions:commit -DnewVersion=${{ github.ref_name }}
      - name: Build Jar
        run: mvn --batch-mode clean package -P cli -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Jar
        run:  mvn --batch-mode deploy -Djacoco.skip=true -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Git add
        run: git add pom.xml
      - name: Commit and push
        uses: actions/checkout@master
        with:
          message: 'Add pom file'
          add: 'pom.xml --force'
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          files: target/commons-ip2-cli-${{ github.ref_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
